Repository ByteTheCookies/CookieFarm, pull requests merged in 2025-05, with the labels that each got.

#93 Enhance Go tooling and add monitoring configuration
  client/.golangci.yml
  client/Makefile
  client/cmd/main.go
  client/internal/api/api.go
  client/internal/config/config.go
  client/internal/executor/run.go
  client/internal/flagparser/parse.go
  client/internal/logger/logger.go
  client/internal/utils/utils.go
  monitoring/docker-compose.yml
  monitoring/process-exporter.yml
  monitoring/process_monitor_dashboard.json
  monitoring/prometheus.yml
  scripts/README.md
  scripts/sysscope_launcher.sh
  server/.golangci.yml
  server/Makefile
  server/cmd/api/main.go
  server/config.yml
  server/go.mod
  server/go.sum
  server/internal/config/config.go
  server/internal/database/database.go
  server/internal/database/insert.go
  server/internal/logger/logger.go
  server/internal/models/models.go
  server/internal/server/core.go
  server/internal/server/handle_api.go
  server/internal/server/handler_view.go
  server/internal/server/limiter.go
  server/internal/server/routes.go
  server/internal/server/server.go
  server/internal/ui/templates.go
  server/internal/utils/utils.go
  server/protocols/protocols.go
  tests/README.md
Labels: bug, enhancement, Clean Code

#95 Release 1.0.1
  BENCHMARKS.md
  LICENSE.md
  README.md
  client/.golangci.yml
  client/Makefile
  client/README.md
  client/cmd/main.go
  client/exploits/example_1.py
  client/exploits/example_2.py
  client/exploits/example_3.py
  client/exploits/example_4.py
  client/exploits/example_5.py
  client/exploits/example_total.py
  client/exploits/utils/exploiter_manager.py
  client/internal/api/api.go
  client/internal/config/config.go
  client/internal/executor/run.go
  client/internal/flagparser/parse.go
  client/internal/logger/logger.go
  client/internal/models/models.go
  client/internal/utils/utils.go
  server/.env.sample
  server/.golangci.yml
  server/Dockerfile
  server/Makefile
  server/cmd/api/main.go
  server/config.yml
  server/docker-compose.yml
  server/go.mod
  server/go.sum
  server/internal/config/config.go
  server/internal/database/database.go
  server/internal/database/insert.go
  server/internal/database/schema.sql
  server/internal/database/select.go
  server/internal/database/update.go
  server/internal/logger/logger.go
  server/internal/models/models.go
  server/internal/server/core.go
  server/internal/server/handle_api.go
  server/internal/server/handler_view.go
  server/internal/server/limiter.go
  server/internal/server/routes.go
  server/internal/server/server.go
  server/internal/ui/templates.go
  server/internal/ui/views/pages/dashboard.html
  server/internal/ui/views/partials/flags_rows.html
  server/internal/utils/utils.go
  server/protocols/cc_http.go
  server/protocols/protocols.go
Labels: bug, enhancement, Clean Code

#97 Enhance WebSocket support and refactor configurations
  client/cmd/main.go
  client/exploits/example_pwn.py
  client/exploits/utils/exploiter_manager.py
  client/go.mod
  client/go.sum
  client/internal/api/api.go
  client/internal/config/config.go
  client/internal/executor/run.go
  client/internal/logger/logger.go
  client/internal/models/models.go
  client/internal/submitter/batch.go
  client/internal/submitter/submitter.go
  client/internal/utils/utils.go
  client/internal/websockets/monitoring.go
  client/internal/websockets/ws.go
  scripts/config.json
  server/assets/js/utils.js
  server/config.yml
  server/go.mod
  server/go.sum
  server/internal/models/models.go
  server/internal/server/routes.go
  server/internal/ui/views/partials/modal.html
  server/internal/websockets/clients-handling.go
  server/internal/websockets/models.go
  server/internal/websockets/ws-event.go
  server/internal/websockets/ws-manager.go
  server/protocols/cc_http.go
  server/public/js/output.min.js
  server/public/js/output.min.js.fiber.gz
  tests/flagchecker.py
Labels: enhancement

#99 Add websocket auto-disconnect and flag collection system
  client/internal/websockets/monitoring.go
  server/config.yml
  server/internal/controllers/stats_controller.go
  server/internal/database/flag_collector.go
  server/internal/database/insert.go
  server/internal/websockets/ws-event.go
Labels: bug, enhancement

#101 Refactor CLI with Cobra and add exploit template generator
  client/Makefile
  client/cmd/attack.go
  client/cmd/create.go
  client/cmd/main.go
  client/cmd/root.go
  client/go.mod
  client/go.sum
  client/internal/api/api.go
  client/internal/config/config.go
  client/internal/executor/run.go
  client/internal/models/models.go
  client/internal/utils/utils.go
  client/internal/websockets/ws.go
  client/main.go
  install.sh
  server/Makefile
  uninstall.sh
Labels: bug, enhancement

#103 Add auto-reload and flag delete functionality
  NOTES.md
  server/.air.toml
  server/assets/css/global.css
  server/assets/js/api.js
  server/internal/database/delete.go
  server/internal/server/handle_api.go
  server/internal/server/routes.go
  server/internal/ui/views/pages/dashboard.html
  server/internal/ui/views/partials/flags_rows.html
  server/internal/ui/views/partials/pagination.html
  server/public/css/output.css
  server/public/css/output.css.fiber.gz
  server/public/js/output.min.js
  server/public/js/output.min.js.fiber.gz
Labels: enhancement

#104 Add modal functionality and UI enhancements
  NOTES.md
  client/cmd/attack.go
  client/cmd/root.go
  client/internal/executor/run.go
  client/internal/submitter/submitter.go
  client/internal/websockets/circuit.go
  client/internal/websockets/ws.go
  server/assets/js/utils.js
  server/internal/config/config.go
  server/internal/server/core.go
  server/internal/server/handle_api.go
  server/internal/server/routes.go
  server/internal/server/server.go
  server/internal/ui/views/pages/dashboard.html
  server/internal/ui/views/partials/modal.html
  server/internal/websockets/ws-event.go
  server/internal/websockets/ws-manager.go
  server/public/css/output.css
  server/public/css/output.css.fiber.gz
  server/public/js/output.min.js
  server/public/js/output.min.js.fiber.gz
Labels: enhancement
